# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts
version: 2.1


jobs:
  test-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.12.8'
    steps:
      - test-dbt-project:
          dp-dbt-project-location: "nubeproduct"
          skip-tests: << pipeline.parameters.dags-or-nbks-only-changes >>
  bi-dags-nubeproduct:
    docker:
      - image: 'cimg/python:3.12.8'
    steps:
      - deploy-dp-dags:
          dp-dags-location: "dags/src"
      - run: echo 'Deployed DAGS for DBT Project into S3 Airflow Artifacts Bucket'
    

workflows:
  allow-merge-dags-changes-only:
    when: << pipeline.parameters.dags-or-nbks-only-changes >>
    jobs:
      - test-dbt-nubeproduct:
          filters:
            branches:
              ignore: main
  
  bi-dbt-production:
    jobs:
      - common-pre:
          filters:
            branches:
              only: main
      - bi-dags-nubeproduct:
          requires:
            - common-pre
          filters:
            branches:
              only: main
          context:
            - dbt-data-products-prd01