# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts
version: 2.1


jobs:
  bi-dags-nubeproduct:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - deploy-dp-dags:
          dp-dags-location: "dags/src"
      - run: echo 'Deployed DAGS for DBT Project into S3 Airflow Artifacts Bucket'

workflows:
  bi-dbt-production:
    jobs:
      - common-pre
      - bi-dags-nubeproduct:
          requires:
            - common-pre
          context:
            - dbt-data-products-prd01