# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts
version: 2.1


jobs:
  test-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run: echo 'Changes on dags do not trigger dbt test'
  bi-dags-nubeproduct:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - deploy-dp-dags:
          dp-dags-location: "dags/src"
      - run: echo 'Deployed DAGS for DBT Project into S3 Airflow Artifacts Bucket'
    

workflows:
  bi-dbt-production:
    jobs:
      - common-pre:
          filters:
            branches:
              only: main
      - test-dbt-nubeproduct:
          filters:
            branches:
              ignore: main
      - bi-dags-nubeproduct:
          requires:
            - common-pre
          filters:
            branches:
              only: main
          context:
            - dbt-data-products-prd01