# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts
version: 2.1

# This command will detect if we're running in a PR context
commands:
  check_if_pr:
    steps:
      - run:
          name: Set PR environment flag
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "export IS_PR=true" >> $BASH_ENV
              echo "Running in a pull request context: $CIRCLE_PULL_REQUEST"
            else
              echo "export IS_PR=false" >> $BASH_ENV
              echo "Not running in a pull request context"
            fi
            source $BASH_ENV

jobs:
  check-pr-status:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - check_if_pr
      - run:
          name: Determine whether to continue
          command: |
            if [ "$IS_PR" = "true" ]; then
              echo "This is a pull request, proceeding with build"
            else
              echo "This is not a pull request, halting workflow"
              circleci-agent step halt
              exit 1
            fi
  test-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.11.9'
    steps:
      - test-dbt-project:
          dp-dbt-project-location: "nubeproduct"
          skip-tests: << pipeline.parameters.dags-or-nbks-only-changes >>
  bi-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.11.9'
    steps:
      - deploy-dbt-project:
          dp-dbt-project-location: "nubeproduct"
      - run: echo 'Deployed Nubeproduct DBT Project into S3 Airflow Artifacts Bucket'
  upload-and-clean-seeds:
    docker:
      - image: 'cimg/python:3.11.9'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:FpEJk6Zv654Vi8ROSs6KlwxRAXwHO8fGbu6oObvrAOg"
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::362686812061:role/CircleCIRoleForOIDC_Generic"
          region: us-east-1
      - run:
          name: Handle Python version
          command: |
            # Remove the .python-version file completely
            rm -f .python-version
      - run:
          name: Setup DBT environment
          command: |
            pip install dbt-core==1.9.1 dbt-databricks==1.9.1
      - create-dbt-profiles
      - run:
          name: Run DBT deps
          command: |
            cd nubeproduct
            dbt deps
      - run:
          name: Run DBT seeds
          command: |
            cd nubeproduct
            dbt seed --target prod
      - run:
          name: Remove csv files from repo
          command: |
            SEEDS_DIR="nubeproduct/seeds"
            CSV_COUNT=$(find "$SEEDS_DIR" -type f -name "*.csv" | wc -l)
            if [ -d "$SEEDS_DIR" ] && [ "$CSV_COUNT" -gt 0 ]; then
              echo "Files uploaded. Removing CSVs from repo..."
              find $SEEDS_DIR -type f -name "*.csv" -exec git rm --cached {} \;
              find $SEEDS_DIR -type f -name "*.csv" -exec rm {} \;
              git config user.email "data-arch@tiendanube.com"
              git config user.name "DBT-svc"
              git remote set-url origin git@github.com:TiendaNube/data-dev-dbt-products.git
              git commit -am "CI: Remove processed CSV seed files from repo"
              git push origin $(git rev-parse --abbrev-ref HEAD)
            else
              echo "No csv files to be removed."
            fi

workflows:
  nubeproduct-dbt-production:
    jobs:
      - common-pre
      - check-pr-status:
          requires:
            - common-pre
          filters:
            branches:
              ignore: main
      - test-dbt-nubeproduct:
          requires:
            - check-pr-status
          filters:
            branches:
              ignore: main
          context:
            - dbt-data-products-prd01
      - upload-and-clean-seeds:
          filters:
            branches:
              only: main
          context:
            - dbt-data-products-prd01
      - bi-dbt-nubeproduct:
          requires:
            - upload-and-clean-seeds
          filters:
            branches:
              only: main
          context:
            - dbt-data-products-prd01