# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts
version: 2.1

# This command will detect if we're running in a PR context
commands:
  check_if_pr:
    steps:
      - run:
          name: Set PR environment flag
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "export IS_PR=true" >> $BASH_ENV
              echo "Running in a pull request context: $CIRCLE_PULL_REQUEST"
            else
              echo "export IS_PR=false" >> $BASH_ENV
              echo "Not running in a pull request context"
            fi
            source $BASH_ENV

jobs:
  check-pr-status:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - check_if_pr
      - run:
          name: Determine whether to continue
          command: |
            if [ "$IS_PR" = "true" ]; then
              echo "This is a pull request, proceeding with build"
            else
              echo "This is not a pull request, halting workflow"
              circleci-agent step halt
              exit 1
            fi
  test-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - test-dbt-project:
          dp-dbt-project-location: "nubeproduct"
      - run: echo 'Deployed Nubeproduct DBT Project into S3 Airflow Artifacts Bucket'
  bi-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - deploy-dbt-project:
          dp-dbt-project-location: "nubeproduct"
      - run: echo 'Deployed Nubeproduct DBT Project into S3 Airflow Artifacts Bucket'

workflows:
  nubeproduct-dbt-production:
    jobs:
      - common-pre
      - check-pr-status:
          requires:
            - common-pre
          filters:
            branches:
              ignore: main
      - test-dbt-nubeproduct:
          requires:
            - check-pr-status
          filters:
            branches:
              ignore: main
          context:
            - dbt-data-products-prd01
      - bi-dbt-nubeproduct:
          filters:
            branches:
              only: main
          context:
            - dbt-data-products-prd01