# Config dedicated for module notebooks
version: 2.1

jobs:
  test-dbt-nubeproduct:
    docker:
      - image: 'cimg/python:3.12.8'
    steps:
      - test-dbt-project:
          dp-dbt-project-location: "nubeproduct"
          skip-tests: << pipeline.parameters.dags-or-nbks-only-changes >>
  deploy-notebooks:
    docker:
      - image: 'cimg/python:3.12.8'
    steps:
      - deploy-nbks-workspace:
          nbk-location: "notebooks/src"
      - run: echo 'Deployed Data Engineer Workspace Notebooks'

workflows:
  allow-merge-dags-changes-only:
    when: << pipeline.parameters.dags-or-nbks-only-changes >>
    jobs:
      - test-dbt-nubeproduct:
          filters:
            branches:
              ignore: main
  deploy-databricks-projects:
    jobs:
      - common-pre
      - deploy-notebooks:
          requires:
            - common-pre
          filters:
            branches:
              only: main