version: 2
models:
  - name: product_issues_and_problems_summary
    description: >
      Contains the summary of Issues and Problems with their respective comments and associated stores. 
    config:
      meta:
        tech_steward: "fabrizio.crivella@tiendanube.com"
        domain: "product"
        business_owner: "Martin Palombo"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - repo_name
            - issue_number
            - store_id
    columns:
      - name: repo_name
        description: Type Issue/Problem
        tests:
          - not_null
      - name: issue_number
        description: Unique identifier of the Issue/Problem.
        tests:
          - not_null
      - name: store_id
        description: Store related to the Issue/Problem.
      - name: state
        description: Status of the Issue/Problem. It can be open or closed.
      - name: author
        description: Creator of the Issue/Problem.
      - name: wip_1_last_updated
        description: >
          Label that identifies if the Issue/Problem is on its first Working in Progress step. Each Issue/Problem
          may or may not be in a WIP status.



  - name: product_platform_mwp_apps_stores
    description: >
      Contains a clean version of the mwp_apps_stores tables after deleting the reinstallations made by the support team
    config:
      meta:
        tech_steward: "fernando.martinez@tiendanube.com"
        domain: "product"
        business_owner: "Nicolas Loreti"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - store_id
            - app_id
    columns:
      - name: store_app_id
        description: Unique store and app ids combination. used for unique key.
        tests:
          - not_null
      - name: store_id
        description: store related to the app_id installed.
        tests:
          - not_null
      - name: app_id
        description: app_id installed by the store.
          - not_null
      - name: app_install_date
        description: date in which the app was installed.
          - not_null
      - name: app_uninstall_date
        description: app in which the app was uninstalled. in case of null, the app is still active.
      - name: sys_admin_created_at
        description: date in which the record was created.
      - name: sys_admin_updated_at
        description: date in which the record was last updated.

        