
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nubeproduct'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'nubeproduct'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  'dbt_date:time_zone': 'America/Argentina/Buenos_Aires'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  nubeproduct: # project name
    # Config indicated by + and applies to all files under models/example/   

    staging:
      +materialized: table
      +schema: staging
      +file_format: delta
      +tags: ["core"]
      +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/staging/"

    intermediate:
      +materialized: ephemeral
      operations:
        +tags: ["operations"]
      partners:
        +tags: ["partners"]
      finance:
        +tags: ["finance"]
      fintech:
        +tags: ["fintech"]
      logistics:
        +tags: ["logistics"]
      marketing:
        +tags: ["marketing"]
      marketing_automation:
        +tags: ["marketing_automation"]
      midmarket:
        +tags: ["midmarket"]
      product:
        +tags: ["product"]
      support:
        +tags: ["support"]

    data_product:
      +materialized: table
      +file_format: delta
      operations:
        +schema: operations
        +tags: ["operations"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/operations/"
      partners:
        +schema: partners
        +tags: ["partners"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/partners/"
      finance:
        +schema: finance
        +tags: ["finance"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/finance/"
      fintech:
        +schema: fintech
        +tags: ["fintech"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/fintech/"
      logistics:
        +schema: logistics
        +tags: ["logistics"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/logistics/"
      marketing:
        +schema: marketing
        +tags: ["marketing"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/marketing/"
      marketing_automation:
        +schema: marketing_automation
        +tags: ["marketing_automation"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/marketing_automation/"
      midmarket:
        +schema: midmarket
        +tags: ["midmarket"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/midmarket/"
      product:
        +schema: product
        +tags: ["product"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/product/"
      support:
        +schema: support
        +tags: ["support"]
        +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_product/support/"

  dbt_artifacts:
    +materialized: table
    +schema: dbt_artifacts
    +file_format: delta
    +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/artifacts/"

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"

seeds:
  nubeproduct:
    +schema: manual
    +file_format: delta
    +location_root: "s3://{{ 'dn-lkh-dev01' if target.name == 'dev' else 'dn-lkh-products-prd01' }}/data-dev-dbt-products/data_manual/"

vars:
  'dbt_date:time_zone': 'America/Argentina/Buenos_Aires'
