{% macro calculate_onboarding_row_hash() %}
    {#-
        Macro para calcular el hash MD5 de una fila en el modelo de onboarding.
        Usado en final_data y existing_with_hash para detectar cambios.
        
        Nota: Los campos deben estar en el mismo orden en ambos lugares.
    #}
    MD5(
        CONCAT_WS('||',
            CAST(store_id AS STRING),
            COALESCE(store_name, ''),
            COALESCE(country, ''),
            COALESCE(CAST(created_at AS STRING), ''),
            COALESCE(CAST(first_payment AS STRING), ''),
            COALESCE(CAST(first_seller_at AS STRING), ''),
            COALESCE(current_segment, ''),
            COALESCE(current_plan, ''),
            COALESCE(vertical, ''),
            COALESCE(CAST(main_user_id AS STRING), ''),
            COALESCE(user_email, ''),
            COALESCE(owner_phone_number, ''),
            COALESCE(phone_from_footer, ''),
            COALESCE(whatsapp_button, ''),
            COALESCE(CAST(COALESCE(qty_admin_access_7d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_admin_access_15d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_admin_access_30d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_admin_access_60d, 0) AS STRING), ''),
            COALESCE(CAST(first_date_admin_access AS STRING), ''),
            COALESCE(CAST(last_date_admin_access AS STRING), ''),
            COALESCE(CAST(first_store_session AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_sessions_7d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_sessions_15d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_sessions_30d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_sessions_60d, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(qty_sessions_90d, 0) AS STRING), ''),
            COALESCE(CAST(last_store_session AS STRING), ''),
            COALESCE(CAST(COALESCE(config_layout, 0) AS STRING), ''),
            COALESCE(layout_name, ''),
            COALESCE(CAST(COALESCE(theme_banner, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(theme_slider, 0) AS STRING), ''),
            COALESCE(CAST(COALESCE(theme_color_change, 0) AS STRING), ''),
            COALESCE(CAST(first_date_config_layout AS STRING), ''),
            COALESCE(CAST(last_date_config_layout AS STRING), ''),
            COALESCE(CAST(COALESCE(config_products, 0) AS STRING), ''),
            COALESCE(CAST(first_date_config_products AS STRING), ''),
            COALESCE(CAST(last_date_config_products AS STRING), ''),
            COALESCE(CAST(COALESCE(config_payment, 0) AS STRING), ''),
            COALESCE(CAST(first_date_config_payment AS STRING), ''),
            COALESCE(CAST(last_date_config_payment AS STRING), ''),
            COALESCE(CAST(COALESCE(config_shipping, 0) AS STRING), ''),
            COALESCE(CAST(first_date_config_shipping AS STRING), ''),
            COALESCE(CAST(last_date_config_shipping AS STRING), ''),
            COALESCE(CAST(first_order AS STRING), ''),
            COALESCE(CAST(time_to_first_order AS STRING), ''),
            COALESCE(CAST(orders_7 AS STRING), ''),
            COALESCE(CAST(orders_15 AS STRING), ''),
            COALESCE(CAST(orders_30 AS STRING), ''),
            COALESCE(CAST(orders_60 AS STRING), ''),
            COALESCE(CAST(orders_90 AS STRING), ''),
            COALESCE(CAST(gmv_30 AS STRING), ''),
            COALESCE(CAST(gmv_60 AS STRING), ''),
            COALESCE(CAST(gmv_90 AS STRING), ''),
            COALESCE(CAST(gmv_dol_30 AS STRING), ''),
            COALESCE(CAST(gmv_dol_60 AS STRING), ''),
            COALESCE(CAST(gmv_dol_90 AS STRING), ''),
            COALESCE(CAST(upgrade_d7 AS STRING), ''),
            COALESCE(CAST(upgrade_d15 AS STRING), ''),
            COALESCE(CAST(upgrade_d30 AS STRING), ''),
            COALESCE(CAST(downgrade_d7 AS STRING), ''),
            COALESCE(CAST(downgrade_d15 AS STRING), ''),
            COALESCE(CAST(downgrade_d30 AS STRING), ''),
            COALESCE(CAST(primeiro_plano AS STRING), ''),
            COALESCE(CAST(max_plan_d7 AS STRING), ''),
            COALESCE(CAST(max_plan_d15 AS STRING), ''),
            COALESCE(CAST(max_plan_d30 AS STRING), ''),
            COALESCE(mkt_source_first_click, ''),
            COALESCE(mkt_subteam_first_click, ''),
            COALESCE(mkt_source_last_click, ''),
            COALESCE(mkt_subteam_last_click, ''),
            COALESCE(merchant_finance_status, ''),
            COALESCE(onboarding_tag, ''),
            COALESCE(CAST(new_payment_probability AS STRING), ''),
            COALESCE(CAST(cutoff_ql AS STRING), ''),
            COALESCE(CAST(COALESCE(blocked_fraud_tag, 0) AS STRING), '')
        )
    )
{% endmacro %}

